apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "rtdr.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: {{ .Values.ingress.hostname | default "rtdr.example.com" }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "rtdr.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
